const menu=document.querySelector('.menu'),nav=document.querySelector('.nav-links');
menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});
document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});
document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const cases={
 india:{title:'IndiaKart',subtitle:'E-commerce Financial & Operational Analytics',html:`<h4>Problem</h4><p>Analyze e-commerce financial and operational performance across orders, customers, payments, returns and inventory.</p><h4>Data</h4><p>216,200 records across 8 relational datasets.</p><h4>Approach</h4><p>Used SQL, Python, Advanced Excel and Power BI for data analysis, KPI analysis and dashboarding.</p><h4>Key findings</h4><ul><li>Returns: <b>30.8%</b></li><li>Cancellations: <b>12.0%</b></li><li>Payment failures: <b>3.5%</b></li><li>Inventory fill rate: <b>92.2%</b></li><li>Premium customers showed <b>1.47×</b> higher CLV.</li></ul>`},
 stream:{title:'StreamFlix',subtitle:'Subscription & Customer Analytics',html:`<h4>Data</h4><p>Approximately 979,000 records across 6 datasets covering subscribers, content, viewing activity, ratings, reviews and watchlists.</p><h4>Analysis</h4><p>Examined watch hours, active-user rate, churn, content completion, monthly recurring revenue (MRR) and average revenue per user (ARPU).</p><h4>Tools</h4><p>SQL · Python · Excel · Power BI</p>`},
 tcs:{title:'TCS Financial Statement Data & Valuation Model',subtitle:'Advanced Excel',html:`<h4>Model</h4><p>Three-statement financial model covering FY2011–FY2025 historical data and FY2026E–FY2030E forecasts.</p><h4>Valuation</h4><ul><li>Base-case WACC: <b>12.89%</b></li><li>Terminal growth: <b>4.5%</b></li><li>Intrinsic value: <b>₹2,397/share</b></li></ul><h4>Components</h4><p>Income Statement · Balance Sheet · Cash Flow Statement · DCF Valuation · Sensitivity Analysis · Comparable Company Analysis · Forecasting</p>`}
};
const modal=document.querySelector('#caseModal'),content=document.querySelector('#modalContent');
document.querySelectorAll('.case-btn').forEach(btn=>btn.addEventListener('click',()=>{const c=cases[btn.dataset.case];content.innerHTML=`<p class="eyebrow">PROJECT CASE</p><h3>${c.title}</h3><p><b>${c.subtitle}</b></p>${c.html}`;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}));
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}
document.querySelector('.close').addEventListener('click',closeModal);document.querySelector('.modal-backdrop').addEventListener('click',closeModal);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
